#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.0.0"
COMMIT = "c19727e21242d1d7e19728d57d72163bf5fdf86d"
MAJOR = 3
MINOR = 0
PATCH = 0
