#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "2.1.0"
COMMIT = "04df549fde492890334ab5e8ce3210ba84af65d5"
MAJOR = 2
MINOR = 1
PATCH = 0
