- repo: local
  hooks:
    - id: assertnews
      name: news file
      entry: assert-news -l
      language: python
      types: [file]
      require_serial: true
      verbose: true
      always_run: true
      pass_filenames: false

    - id: licensing
      name: licensing
      entry: license-files
      language: python
      types: [file]
      require_serial: true
      always_run: true
      verbose: true
      pass_filenames: false

    - id: black
      name: black
      entry: black
      language: python
      types: [python]
      require_serial: true

    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
      require_serial: true

    - id: mypy
      name: mypy
      entry: mypy src/mbed_tools
      language: python
      types: [python]
      require_serial: true
      pass_filenames: false

    - id: pytest
      name: pytest
      entry: pytest -vvv
      language: python
      types: [python]
      pass_filenames: false
      always_run: true

