repos:
  - repo: https://github.com/ARMmbed/mbed-tools-ci-scripts.git
    rev: 6b22e59771793679854ae520c9f109fa5385dc6d
    hooks:
      - id: licensing

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        entry: mypy src
        pass_filenames: false
