repos:
  - repo: https://github.com/kdeyev/licenseheaders.git
    rev: 'master'
    hooks:
      - id: licenseheaders
        exclude: \.yaml$|\.yml$
        args: ["-s", "ci_scripts/licenseheaders.json", "-t",
        "ci_scripts/templates/.copyright.tmpl", "-cy", "-f"]

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        entry: mypy src
        pass_filenames: false
