#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.4.0"
COMMIT = "231dbc443bc14b2932f68fda23a6e5fedb94a481"
MAJOR = 3
MINOR = 4
PATCH = 0
