#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.2.2"
COMMIT = "7e648cbc7ee039cd770b8956bb0a5b25dca2473b"
MAJOR = 3
MINOR = 2
PATCH = 2
