#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.3.0"
COMMIT = "fe6acb4ae202bcb4262239b7188816eb41e26e98"
MAJOR = 3
MINOR = 3
PATCH = 0
