parameters:
  message: 'Release'
  releaseType: 'development'
  currentBranch: ''

steps:
  - script: |
      git switch -c ${{ parameters.currentBranch }} --track origin/${{ parameters.currentBranch }}
      tox -e release -- --release-type=${{ parameters.releaseType }} -vv
    displayName: ${{ parameters.message }}
    env:
      GIT_TOKEN: $(GIT_TOKEN)
      TWINE_USERNAME: $(TWINE_USERNAME)
      TWINE_PASSWORD: $(TWINE_PASSWORD)
      IGNORE_PYPI_TEST_UPLOAD: $(IGNORE_PYPI_TEST_UPLOAD)
